version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xkorin_api
    volumes:
      - .:/workspace:cached
      - /workspace/node_modules
    ports:
      - "4005:4005"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: Xkorin
    volumes:
      - mongodb-data:/data/db

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mongodb-data:
