version: '3.8'

services:
  app:
    image: nkot20/xkorin-backend:latest
    ports:
      - "4005:4005"
    environment:
      - NODE_ENV=production
    volumes:
      - /home/xkorin/backend.git/.env:/workspace/.env
    restart: always
